In [0]:
import numpy as np
import random
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.linear_model


X = [[1, 0],
                  [0, 1],
                  [0, -1],
                  [-1, 0]]

y = [0, 1, 1, 0]

        
        
class1_x1 = np.array(random.sample(range(2, 100), 48))
class1_x2 = np.array(np.random.rand(48))

random_x1c1 = np.array(random.sample(range(0, 48), 20))
random_x2c1 = np.array(random.sample(range(0, 48), 20))
class1_x1[random_x1c1] = class1_x1[random_x1c1]*-1
class1_x2[random_x2c1] = class1_x2[random_x2c1]*-1

class2_x1 = np.array(np.random.rand(48))
class2_x2 = np.array(random.sample(range(2, 100), 48))

random_x1c2 = np.array(random.sample(range(0, 48), 20))
random_x2c2 = np.array(random.sample(range(0, 48), 20))
class2_x1[random_x1c2] = class2_x1[random_x1c2]*-1
class2_x2[random_x2c2] = class2_x2[random_x2c2]*-1

for i in range(len(class1_x1)):
  X.append([class1_x1[i], class1_x2[i]])
  y.append(0)

for i in range(len(class1_x1)):
  X.append([class2_x1[i], class2_x2[i]])
  y.append(1)

X = np.array(X)
Y = np.array(y)

In [0]:
X, Y = X.T, Y.reshape(1, Y.shape[0])

In [0]:
def layer_sizes(X, Y):
    """
    Arguments:
    X -- input dataset of shape (input size, number of examples)
    Y -- labels of shape (output size, number of examples)
    
    Returns:
    n_x -- the size of the input layer
    n_h -- the size of the hidden layer
    n_y -- the size of the output layer
    """
    n_x = X.shape[0] # size of input layer`
    n_h = 2
    n_y =Y.shape[0] # size of output layer
    return (n_x, n_h, n_y)


In [0]:
def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    params -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
        
    W1 = 2*np.random.random((n_h,n_x)) -1
    b1 = np.zeros(shape=(n_h, 1))
    
    W2 = 2*np.random.random((n_h,n_h)) -1
    b2 = np.zeros(shape=(n_h, 1))
    
    W3 = 2*np.random.random((n_y,n_h)) -1
    b3 = np.zeros(shape=(n_y, 1))
    
    print (W2.shape)
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2,
                  "W3": W3,
                  "b3": b3}
    
    return parameters


In [0]:
def forward_propagation(X, parameters):
    """
    Argument:
    X -- input data of size (n_x, m)
    parameters -- python dictionary containing your parameters (output of initialization function)
    
    Returns:
    A2 -- The sigmoid output of the second activation
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2"
    """
    # Retrieve each parameter from the dictionary "parameters"
    W1 = parameters['W1']
    b1 = parameters['b1']
    W2 = parameters['W2']
    b2 = parameters['b2']
    W3 = parameters['W3']
    b3 = parameters['b3']
    
    # Implement Forward Propagation to calculate A2 (probabilities)
    Z1 = np.matmul(W1, X) + b1
    A1 = sigmoid(Z1)
    Z2 = np.matmul(W2, A1) + b2
    A2 = sigmoid(Z2)
    Z3 = np.matmul(W3, A2) + b3
    A3 = sigmoid(Z3)
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2,
             "Z3": Z3,
             "A3": A3}
    
    return A3, cache

In [0]:
def compute_cost(A3, Y, parameters):
    """
    
    Arguments:
    A3 -- The sigmoid output of the second activation, of shape (1, number of examples)
    Y -- "true" labels vector of shape (1, number of examples)
    parameters -- python dictionary containing your parameters W1, b1, W2 and b2
    
    Returns:
    cost -- cross-entropy cost given equation (13)
    """
    
    m = Y.shape[1] # number of example

    # Compute the cross-entropy cost
    logprobs = np.multiply(np.log(A3), Y) + np.multiply((1 - Y), np.log(1 - A3))
    cost = - np.sum(logprobs) / m    
    
    cost = np.squeeze(cost)     # makes sure cost is the dimension we expect. 
                                # E.g., turns [[17]] into 17 
    
    return cost

In [0]:
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

  
def backward_propagation(parameters, cache, X, Y):
    """
    Implement the backward propagation using the instructions above.
    
    Arguments:
    parameters -- python dictionary containing our parameters 
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2".
    X -- input data of shape (2, number of examples)
    Y -- "true" labels vector of shape (1, number of examples)
    
    Returns:
    grads -- python dictionary containing your gradients with respect to different parameters
    """
    m = X.shape[1]
    
    # First, retrieve W1 and W2 from the dictionary "parameters".
    W1 = parameters['W1']
    W2 = parameters['W2']
    W3 = parameters['W3']
        
    # Retrieve also A1 and A2 from dictionary "cache".
    A1 = cache['A1']
    A2 = cache['A2']
    A3 = cache['A3']
    
    Z1 = cache['Z1']
    Z2 = cache['Z2']
    Z3 = cache['Z3']
    
    # Backward propagation: calculate dW1, db1, dW2, db2. 

    dZ3 = A3-Y
    dW3 = (1./m) * np.matmul(dZ3, A2.T)
    db3 = (1./m) * np.sum(dZ3, axis=1, keepdims=True)
    
    dA2 = np.matmul(W3.T,dZ3)
    dZ2 = dA2 * sigmoid(Z2) * (1 - sigmoid(Z2))
    dW2 = (1./m) * np.matmul(dZ2, A1.T)
    db2 = (1./m) * np.sum(dZ2, axis=1, keepdims=True)
    
    dA1 = np.matmul(W2.T, dZ2)
    dZ1 = dA1 * sigmoid(Z1) * (1 - sigmoid(Z1))
    dW1 = (1./m) * np.matmul(dZ1, X.T)
    db1 = (1./m) * np.sum(dZ1, axis=1, keepdims=True)
    
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2,
             "dW3": dW3,
             "db3": db3}
    
    return grads

In [0]:
def update_parameters(parameters, grads, learning_rate = 1):
    """
    Updates parameters using the gradient descent update rule given above
    
    Arguments:
    parameters -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients 
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
    """
    # Retrieve each parameter from the dictionary "parameters"

    W1 = parameters['W1']
    b1 = parameters['b1']
    W2 = parameters['W2']
    b2 = parameters['b2']
    W3 = parameters['W3']
    b3 = parameters['b3']

    
    # Retrieve each gradient from the dictionary "grads"
    dW1 = grads['dW1']
    db1 = grads['db1']
    dW2 = grads['dW2']
    db2 = grads['db2']
    dW3 = grads['dW3']
    db3 = grads['db3']

    
    # Update rule for each parameter

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    W3 = W3 - learning_rate * dW3
    b3 = b3 - learning_rate * db3
    
    #print (W2.shape)
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2,
                  "W3": W3,
                  "b3": b3}
    
    return parameters


In [0]:
def nn_model(X, Y, n_h, num_iterations = 10000, print_cost=False):
    """
    Arguments:
    X -- dataset of shape (2, number of examples)
    Y -- labels of shape (1, number of examples)
    n_h -- size of the hidden layer
    num_iterations -- Number of iterations in gradient descent loop
    print_cost -- if True, print the cost every 1000 iterations
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to predict.
    """
    
    np.random.seed(3)
    n_x = layer_sizes(X, Y)[0]
    n_y = layer_sizes(X, Y)[2]
    
    # Initialize parameters, then retrieve W1, b1, W2, b2. Inputs: "n_x, n_h, n_y". Outputs = "W1, b1, W2, b2, parameters".
    parameters = initialize_parameters(n_x, n_h, n_y)
    W1 = parameters['W1']
    b1 = parameters['b1']
    W2 = parameters['W2']
    b2 = parameters['b2']
    W3 = parameters['W3']
    b3 = parameters['b3']
    
    # Loop (gradient descent)

    for i in range(0, num_iterations+1):
         
        # Forward propagation. Inputs: "X, parameters". Outputs: "A2, cache".
        A2, cache = forward_propagation(X, parameters)
        
        # Cost function. Inputs: "A2, Y, parameters". Outputs: "cost".
        cost = compute_cost(A2, Y, parameters)
 
        # Backpropagation. Inputs: "parameters, cache, X, Y". Outputs: "grads".
        grads = backward_propagation(parameters, cache, X, Y)
 
        # Gradient descent parameter update. Inputs: "parameters, grads". Outputs: "parameters".
        parameters = update_parameters(parameters, grads)
        
        # Print the cost every 1000 iterations
        if print_cost and i % 1000 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))

    return parameters


In [0]:
def predict(parameters, X):
    """
    Using the learned parameters, predicts a class for each example in X
    
    Arguments:
    parameters -- python dictionary containing your parameters 
    X -- input data of size (n_x, m)
    
    Returns
    predictions -- vector of predictions of our model (red: 0 / blue: 1)
    """
    
    # Computes probabilities using forward propagation, and classifies to 0/1 using 0.5 as the threshold.
    ### START CODE HERE ### (≈ 2 lines of code)
    A2, cache = forward_propagation(X,parameters)
    predictions = A2 > 0.5
    ### END CODE HERE ###
    
    return predictions

In [0]:
# Build a model with a n_h-dimensional hidden layer
parameters = nn_model(X, Y, n_h = 3, num_iterations = 5000, print_cost=True)

(3, 3)
Cost after iteration 0: 0.694972
Cost after iteration 1000: 0.015882
Cost after iteration 2000: 0.005903
Cost after iteration 3000: 0.003597
Cost after iteration 4000: 0.002582
Cost after iteration 5000: 0.002013


In [0]:
predictions = predict(parameters, X)
print ('Accuracy: %d' % float((np.dot(Y,predictions.T) + np.dot(1-Y,1-predictions.T))/float(Y.size)*100) + '%')


Accuracy: 100%


##Minimum Number of layers required for 100% classification -  4

In [0]:


W1 = parameters['W1']
b1 = parameters['b1']
W2 = parameters['W2']
b2 = parameters['b2']
W3 = parameters['W3']
b3 = parameters['b3']

##Weights 

In [0]:
print ("Weight for layer 1\n\n" , W1)

Weight for layer 1

 [[-2.51706688  0.88791395]
 [-3.5043297   1.13917446]
 [ 1.63522824  4.01357372]]


In [0]:
print ("Bias for layer 1\n\n" , b1)

Bias for layer 1

 [[ 0.58770871]
 [ 1.0726067 ]
 [-2.78339359]]


In [0]:
print ("Weight for layer 2\n\n" , W2)

Weight for layer 2

 [[-3.81384199 -3.44639334 -5.37715882]
 [-3.50655894 -5.8449524   6.40830704]
 [-2.15141904 -3.31904782  8.31979066]]


In [0]:
print ("Bias for layer 2\n\n" , b2)

Bias for layer 2

 [[ 1.67513854]
 [-2.20559248]
 [ 1.3557318 ]]


In [0]:
print ("Weight for layer 3\n\n" , W3)

Weight for layer 3

 [[  6.70307033 -13.21091358  12.28892327]]


In [0]:
print ("Bias for layer 3\n\n" , b3)

Bias for layer 3

 [[-6.10121865]]


In [0]:
W2.shape

(3, 3)

## Learning rate used - 0.9

##Sigmoidal Slope Parameter - 1

## Number of epochs for convergence - 5000